apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hellow.fullname" . }}
  labels: 
  app: {{ template "hellow.fullname" . }}
  component: {{ template "hellow.fullname" . }}
  release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
     type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "hellow.fullname" . }}
      component: {{ template "hellow.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "hellow.fullname" . }}
      labels:
        app: {{ template "hellow.fullname" . }}
        component: {{ template "hellow.fullname" . }}
        release: {{ .Release.Name }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
           - matchExpressions:
             - key: kubernetes.io/hostname
               operator: In
               values:
                - {{ .Values.Node.hostname}}
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: Always
    livenessProbe:
       initialDelaySeconds: 60
       tcpSocket:
           port: 80
    name: {{ template "hellow.fullname" . }}
    readinessProbe:
       httpGet:
            path: /
            port: 80
       initialDelaySeconds: 5
    securityContext:
        privileged: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true 